name: Deploy Azure Functions (staging)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: empirecommandcenter-altus-staging
  AZURE_RESOURCE_GROUP: empirecommandcenter-altus-staging_group
  PYTHON_VERSION: "3.11"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Configure app for remote build
        run: |
          az functionapp config appsettings set \
            --resource-group "${{ env.AZURE_RESOURCE_GROUP }}" \
            --name "${{ env.AZURE_FUNCTIONAPP_NAME }}" \
            --settings FUNCTIONS_WORKER_RUNTIME=python FUNCTIONS_EXTENSION_VERSION=~4 \
                       SCM_DO_BUILD_DURING_DEPLOYMENT=true ENABLE_ORYX_BUILD=true

      - name: Ensure Linux Python runtime
        run: |
          az functionapp config set \
            --resource-group "${{ env.AZURE_RESOURCE_GROUP }}" \
            --name "${{ env.AZURE_FUNCTIONAPP_NAME }}" \
            --linux-fx-version "Python|${{ env.PYTHON_VERSION }}"

      - name: Deploy Functions (remote build)
        uses: azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: .
          respect-funcignore: true
          remote-build: true
          scm-do-build-during-deployment: true
          enable-oryx-build: true

      - name: Smoke test
        continue-on-error: true
        run: |
          BASE="https://${{ env.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net"
          echo "GET $BASE/api/ping"
          curl -i --max-time 20 "$BASE/api/ping" || true
          echo "GET $BASE/api/legal/export/cases"
          curl -i --max-time 20 "$BASE/api/legal/export/cases" || true
          echo "GET $BASE/api/portfolio/properties"
          curl -i --max-time 20 "$BASE/api/portfolio/properties" || true
